name: Publish API

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Github Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build Image
        run: |
          docker build ./express-api -t ghcr.io/madhummitha/docker-express-api:latest -t ghcr.io/madhummitha/docker-express-api:${{github.sha}}
          docker push ghcr.io/madhummitha/docker-express-api:latest 
          docker push ghcr.io/madhummitha/docker-express-api:${{github.sha}}
